name: Deploy to Digital Ocean

on:
  push:
    branches: [ main ]

env:
  REGISTRY: registry.digitalocean.com/inventory-ballet-reg
  IMAGE_NAME: inventory-app
  CONTAINER_NAME: inventory-app

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}

      - name: Log in to DO Container Registry 
        run: doctl registry login --expiry-seconds 600

      - name: Build container image
        run: |
          docker build \
            --build-arg VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }} \
            --build-arg VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }} \
            -t $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7) .

      - name: Push image to DO Container Registry
        run: docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Set Short SHA
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | head -c7)" >> $GITHUB_ENV

      - name: Deploy to Node 1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_1 }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Stop keys to prevent conflicts
            export IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}
            # Login
            echo ${{ secrets.DO_TOKEN }} | docker login registry.digitalocean.com -u do-user --password-stdin
            # Pull
            docker pull $IMAGE
            # Stop old
            docker stop ${{ env.CONTAINER_NAME }} || true
            docker rm ${{ env.CONTAINER_NAME }} || true
            # Run
            docker run -d \
              --name ${{ env.CONTAINER_NAME }} \
              --restart unless-stopped \
              -p 80:80 \
              $IMAGE

      - name: Deploy to Node 2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_2 }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}
            echo ${{ secrets.DO_TOKEN }} | docker login registry.digitalocean.com -u do-user --password-stdin
            docker pull $IMAGE
            docker stop ${{ env.CONTAINER_NAME }} || true
            docker rm ${{ env.CONTAINER_NAME }} || true
            docker run -d \
              --name ${{ env.CONTAINER_NAME }} \
              --restart unless-stopped \
              -p 80:80 \
              $IMAGE
